export default {
    blockquote: 'Blockquote',
    bold: 'Bold',
    bulletList: 'Unordered List',
    code: 'Code',
    codeBlock: 'Code Block',
    heading: 'Heading',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    heading4: 'Heading 4',
    heading5: 'Heading 5',
    heading5: 'Heading 6',
    horizontalRule: 'Horizontal Rule',
    image: 'Image',
    italic: 'Italic',
    link: 'Link',
    listItem: 'List Item',
    orderedList: 'Ordered List',
    paragraph: 'Paragraph',
    strike: 'Strike',
    subscript: 'Subscript',
    superscript: 'Superscript',
    table: 'Table',
    tableCell: 'Table Cell',
    tableHeader: 'Table Header',
    tableRow: 'Table Row',
    underline: 'Underline',
};