export default {
    blockquote: 'Blockquote',
    bold: 'Bold',
    code_block: 'Code Block',
    code: 'Code',
    heading_1: 'Heading 1',
    heading_2: 'Heading 2',
    heading_3: 'Heading 3',
    heading_4: 'Heading 4',
    heading_5: 'Heading 5',
    heading_5: 'Heading 6',
    horizontal_rule: 'Horizontal Rule',
    image: 'Image',
    italic: 'Italic',
    link: 'Link',
    list_item: 'List Item',
    ordered_list: 'Ordered List',
    paragraph: 'Paragraph',
    strike: 'Strike',
    subscript: 'Subscript',
    superscript: 'Superscript',
    table_cell: 'Table Cell',
    table_header: 'Table Header',
    table_row: 'Table Row',
    table: 'Table',
    underline: 'Underline',
    unordered_list: 'Unordered List',
};