title: Statamic Bard Texstyle
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: main
aux_links:
  "Statamic Bard Texstyle on GitHub":
    - "https://github.com/jacksleight/statamic-bard-texstyle"